/// <reference types="vitest" />
import path from 'node:path';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, '.'),
    },
  },
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./tests/setup.ts'],
    include: ['tests/**/*.test.{ts,tsx}'],
    css: false,
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html'],
      // Hand-written app code only. See web/COVERAGE.md for the rationale
      // behind every exclusion below.
      include: ['app/**', 'src/**'],
      exclude: [
        // Generated OpenAPI types — no executable lines, regenerated by `npm run gen:api`.
        'src/types/api.ts',
        // Type-only declaration files.
        '**/*.d.ts',
        // Config / build wiring.
        '**/*.config.*',
        '**/postcss.*',
        '**/next-env.d.ts',
        // Playwright e2e specs + the Vitest test suite + its mocks/setup.
        'e2e/**',
        'tests/**',
        // MSW server bootstrap — test-only infrastructure, exercised indirectly.
        'src/lib/mocks/**',
      ],
      thresholds: {
        lines: 100,
      },
    },
  },
});
